// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function ApprovePlan(arg1:string,arg2:string):Promise<void>;

export function BinaryStatus():Promise<Record<string, boolean>>;

export function DownloadAssets():Promise<void>;

export function GetSettings():Promise<settings.Settings>;

export function IsLoggedIn():Promise<boolean>;

export function Logout():Promise<void>;

export function PollLogin(arg1:string):Promise<string>;

export function RejectPlan(arg1:string):Promise<boolean>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SendChat(arg1:string,arg2:string):Promise<void>;

export function Speak(arg1:string):Promise<string>;

export function StartLogin():Promise<Record<string, any>>;

export function Transcribe(arg1:string):Promise<string>;
