// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApprovePlan(arg1, arg2) {
  return window['go']['main']['App']['ApprovePlan'](arg1, arg2);
}

export function BinaryStatus() {
  return window['go']['main']['App']['BinaryStatus']();
}

export function DeletePersonalKey() {
  return window['go']['main']['App']['DeletePersonalKey']();
}

export function DownloadAssets() {
  return window['go']['main']['App']['DownloadAssets']();
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetPersonalKey() {
  return window['go']['main']['App']['GetPersonalKey']();
}

export function GetProvider() {
  return window['go']['main']['App']['GetProvider']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PollLogin(arg1) {
  return window['go']['main']['App']['PollLogin'](arg1);
}

export function RejectPlan(arg1) {
  return window['go']['main']['App']['RejectPlan'](arg1);
}

export function SavePersonalKey(arg1) {
  return window['go']['main']['App']['SavePersonalKey'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendChat(arg1, arg2) {
  return window['go']['main']['App']['SendChat'](arg1, arg2);
}

export function SetProvider(arg1, arg2) {
  return window['go']['main']['App']['SetProvider'](arg1, arg2);
}

export function Speak(arg1) {
  return window['go']['main']['App']['Speak'](arg1);
}

export function StartLogin() {
  return window['go']['main']['App']['StartLogin']();
}

export function ToggleAgent(arg1, arg2) {
  return window['go']['main']['App']['ToggleAgent'](arg1, arg2);
}

export function Transcribe(arg1) {
  return window['go']['main']['App']['Transcribe'](arg1);
}
